#-------------------------------------------------------------------------
# Manifest File to create AWS EKS Cluster with ManagedNodes
#
# eksctl create cluster -f eks-cluster-config.v2.yaml --profile user1-profile
# eksctl delete cluster -f eks-cluster-config.v2.yaml --profile user1-profile
# eksctl update cluster -f eks-cluster-config.v2.yaml --profile user1-profile
#
# Copyleft (c) by David Izhak 2023
#-------------------------------------------------------------------------
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-prod
  version: "1.28"
  region : eu-west-1
  
#vpc:
# subnets:
#   public:
#      eu-west-1a: { id: subnet-052450e8205b756ae }
#      eu-west-1b: { id: subnet-083ba192f0a91e893 }
#
#   private:
#      eu-west-1a: { id: subnet-0bdc7681fe8f09915 }
#      eu-west-1b: { id: subnet-0670735d9144585d3 }

managedNodeGroups:
  - name             : worker-group-1
    instanceType     : t2.micro
    desiredCapacity  : 2
    labels           : { role: worker1 }   
    volumeSize       : 50
    privateNetworking: true
    
  - name             : worker-group-2
    instanceType     : t2.micro
    desiredCapacity  : 3
    volumeSize       : 60
    labels           : { role: worker2 }    
    privateNetworking: true    
