#---------------------------------------------------------------------
# Manifest File to create Multi Container Pods Deployment with Service
#
# Copyleft (c) by David Izhak 2023
#---------------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-deployment-multi-pod
  labels:
    app  : my-k8s-php-deployment
    env  : prod
    owner: David-Izhak
spec:
  replicas: 3
  selector:
    matchLabels:
      project: k8s-app
  template:
    metadata:
      labels:
        project: k8s-app
    spec:
      containers:
        - name : my-web
          image: davidizhak/k8sphp:latest
          ports:
            - containerPort: 80   # Port on Pod

        - name : not-my-web
          image: tomcat:8.5.38
          ports:
            - containerPort: 8080  # Port on Pod

---
apiVersion: v1
kind: Service
metadata:
  name: my-multi-pods-service
  labels:
     env  : prod
     owner: David-Izhak
spec:
  type: LoadBalancer
  selector:
    project: k8s-app
  ports:
    - name      : my-web-app-listener
      protocol  : TCP
      port      : 80
      targetPort: 80

    - name      : not-my-web-app-listener
      protocol  : TCP
      port      : 8888
      targetPort: 8080
